---
title: "The Michelin Star Dream"
author: "Ziyu Chen zc2333, Tina Zhao nz2333, Huijun Xiao hx2306, Xinyan Zhou xz2981"
output: github_document
---
### The motivation for this project:   
Michelin stars are what every chef is looking for! Even the most renowned chefs will be worried about losing stars, and even cry after losing one or two stars. However, the majority of chefs are devoting their lives just for one star. It is obvious that Michelin stars are important for chefs, but the controversies around this guide always exist.    

In this project, we would like to explore the following questions:    
+ To what extent can Michelin 3-Star restaurants keep their stars?    
+ To what extent does the Michelin Guide overlap with other famous food rankings like the world’s 50 best restaurants?    
+ Does the Michelin Guide have some preferences for some cuisines?     
+ Is a higher Michelin ranking associated with higher rating in other social media (Yelp, Open Table)?    
    
### The anticipated data sources:    
We plan to use the data set from kaggle (https://www.kaggle.com/jackywang529/michelin-restaurants) and integrate data from Michelin's official website.       
    
### The planned analyses / visualizations / coding challenges:  
We plan to run descriptive analyses first and produce a baseline characteristics table and do some geographic comparison for the restaurants. We will also analyze the relationship between the cuisine types and prices, cuisine types and star ratings of restaurants to see if there is an association between the variables. The analysis results will be delivered using graphs. Using the latitude and longitude data available we will also plot a map showing the Michelin starred restaurant locations. Using rating data from other websites, we plan to combine datasets and find the association between Michelin star and regular restaurant ratings. The coding challenges could be to extract useful data from other websites, recode variables in appropriate ways and merge the datasets efficiently.   
    
### Intended final products:       
Relevant data will be visualized in the form of interactive graphs on a dashboard. In the end, we want a series of dashboards that provide insights on the aforementioned topics and display our findings clearly. Geo heat map will be provided to display data points on a real US map and signify areas of low and high density if necessary.     
      
### The planned timeline :    
| Date     | Description                                                     |
|----------|-----------------------------------------------------------------|
| 11/13    | _Submit Proposal_                                               |
| 11/15    | _Review Proposal; Start Data Cleaning; Combine Datasets_        |
| 11/16-19 | _Project Review Meeting_                                        |
| 11/20    | _Add Supplementary Datasets/ Research Questions; Finalize Data_ |
| 11/22-29 | _Start Analysis / Website Construction_                         |
| 12/4     | _Start Written Report; Finish Webpage and Screencast_           |
| 12/11    | _Report, Webpage and Screencast Due Date_                       |    
